MORSE_CODE_MAX_LENGTH = 13


KEYBOARD_MODE = 0
MOUSE_MODE = 1

MOUSE_MOVE_RIGHT      = 1
MOUSE_MOVE_LEFT       = 2
MOUSE_MOVE_UP         = 3
MOUSE_MOVE_DOWN       = 4
MOUSE_MOVE_LEFT_UP    = 5
MOUSE_MOVE_RIGHT_UP   = 6
MOUSE_MOVE_LEFT_DOWN  = 7
MOUSE_MOVE_RIGHT_DOWN = 8
MOUSE_CLICK_RIGHT     = 9
MOUSE_CLICK_LEFT      = 10
MOUSE_DB_CLICK_RIGHT  = 11
MOUSE_DB_CLICK_LEFT   = 12

SHORTCUT_CTRL_C  = 0
SHORTCUT_CTRL_V  = 1
SHORTCUT_WIN_TAB = 2
SHORTCUT_WIN_H   = 3

REG_KEYBOARD_CHAR = 0
SPL_KEYBOARD_CHAR = 1
MOUSE_CMD         = 2

ACTIVE_HIGH = 0
ACTIVE_LOW  = 1

BUZZER_TYPE = ACTIVE_HIGH